name: First Github Action 
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello world"
      - name: Run Multiline shell script 
        run: |
            echo "First output"
            echo "Second output"
